question_data = {"response_code": 0, "results": [{"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                  "question": "A bear does NOT defecate during hibernation. ",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. "
                                                              "Pac-Man&quot; have completely different behavior.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Japanese Anime &amp; Manga",
                                                  "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Cartoon &amp; Animations",
                                                  "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Celebrities",
                                                  "question": "Marilyn Monroe was born on July 1, 1926.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Japanese Anime &amp; Manga",
                                                  "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Music",
                                                  "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "You can legally drink alcohol while driving in Mississippi.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Art",
                                                  "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Board Games",
                                                  "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Japanese Anime &amp; Manga",
                                                  "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Books",
                                                  "question": "The book 1984 was published in 1949.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Luigi is taller than Mario?", "correct_answer": "True",
                                                  "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "The color orange is named after the fruit.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science: Mathematics",
                                                  "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                                  "question": "Greenland is covered with grass and Iceland covered with ice.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Film",
                                                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science: Mathematics",
                                                  "question": "The sum of any two odd integers is odd.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Film",
                                                  "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "Jingle Bells was originally meant for Thanksgiving",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Music",
                                                  "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "History",
                                                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Music",
                                                  "question": "Eurobeat is primarily an Italian genre of music.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Comics",
                                                  "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science: Computers",
                                                  "question": "RAM stands for Random Access Memory.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "History",
                                                  "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Minecraft can be played with a virtual reality headset.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                  "question": "The Killer Whale is considered a type of dolphin.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Books",
                                                  "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Activision created Battlefield 1.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Music",
                                                  "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Music",
                                                  "question": "Scatman John&#039;s real name was John Paul Larkin.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge", "question": "Pluto is a planet.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                  "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science &amp; Nature",
                                                  "question": "An atom contains a nucleus.", "correct_answer": "True",
                                                  "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Politics",
                                                  "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science &amp; Nature",
                                                  "question": "An Astronomical Unit is the distance between Earth and the Moon.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]}
